name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          python -mpip install poetry codecov
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with pylint
        run: |
          poetry run pylint django_simple_task
      - name: Test with pytest
        run: |
          poetry run py.test --cov=./django_simple_task/
      - name: Upload coverage to codecov
        run: |
          codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
